# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Munge::App"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "layout"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"


# template engine
# simple: default and very basic template engine
# template_toolkit: TT

# template: "simple"

#template: "tiny"

template: "template_toolkit"
engines:
  template_toolkit:
    COMPILE_DIR: 'caches/templates'
    COMPILE_EXT: '.ttc'
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'

# session, memcached over socket

session: "YAML"

#session: "memcached"
#memcached_servers: "/var/sock/memcached"

plugins:
    DBIC:
        schema_class: Munge::Schema
        dsn:  dbi:mysql:munge
        user: munge
        pass: munge
        options:
          RaiseError: 1
          PrintError: 1
